# Generated by Django 5.0.6 on 2024-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('pname', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('ptype', models.CharField(choices=[('clothing', 'clothing'), ('footwear', 'footwear'), ('electronics', 'electroincs'), ('home', 'home')], max_length=50)),
            ],
        ),
    ]
